[tool.ruff]
# match black
line-length = 88
target-version = "py39"

lint.select = [
    "ALL", # include all the rules, including new ones
]
lint.extend-select = ["I"]
lint.ignore = [
    #### modules
    "ANN", # flake8-annotations
    "COM", # flake8-commas
    "C90", # mccabe complexity
    "DJ",  # django
    "EXE", # flake8-executable
    "T10", # debugger
    "TID", # flake8-tidy-imports

    #### specific rules
    "D100",   # ignore missing docs
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D200",
    "D205",
    "D211",
    "D212",
    "D400",
    "D401",
    "D415",
    "E402",   # false positives for local imports
    "E501",   # line too long
    "ISC001",
    "TRY003", # external messages in exceptions are too verbose
    "G004",   # f-strings in logs (Our project is too small to care about this)
    "TD002",
    "TD003",
    "FIX002", # too verbose descriptions of todos
    "S101",   # disable warnings about assert statements in tests
    "PLR0911", # Too many return statements
    "PLR0912", # Too many branches
    "PLR0913", # Too many arguments in function definition
    "PLR0915", # Too many statements
]

[tool.ruff.lint.per-file-ignores]
"*/tests/**/*.py" = [
    "ARG001",   # Unused function arguments
    "ARG002",   # Unused method arguments
    "PLR2004",  # Magic value used in comparison
    "PT011",    # pytest.raises() is too broad
    "PTH100",   # Path handling
    "PTH120",   # Use Path.parent instead of dirname
    "F811",     # Redefinition of unused name
]

# Additional configuration options can be added here.